### ISSUE TITLE
Опечатка

### ISSUE THREAD

**Issue by binakot** [Hexlet/ru-local-communities#83]
Golang Krasnodar (meetup): Сообщество Go **a** lang-разработчиков Краснодара.

**Comment by Yur-ok** [comment]
Взял в работу.

**Comment by antlu** [comment]
Можно закрывать.

**Comment by binakot** [comment]
> Можно закрывать.

А есть ссылка на коммит/PR с исправлениями?

**Comment by antlu** [comment]
https://github.com/Hexlet/ru-local-communities/pull/88/files#diff-04c6e90faac2675aa89e2176d2eec7d8R56
